pipeline {
    agent {
        label 'slave'
    }
    stages {
        stage('Hello') {
            steps {
                sh 'java --version'
                echo 'get working directory'
                echo 'pwd'
            }
        }
    }
}
